### ISSUE TITLE
Fix : login back button bug 

### ISSUE THREAD

**Issue by sourabhrathour45** [Makaan-Mates/mask#9]

**Comment by Shadev-Kumar** [comment]
Can you give more description?

**Comment by sourabhrathour45** [comment]
Solved this issue - 
Here is the reference - https://stackoverflow.com/questions/72248829/how-to-prevent-user-from-going-back-in-react-router-v6

`const navigate = useNavigate();

...

const loginHandler = () => {
  ... authentication business logic ...

  // if authenticated
  navigate(targetPath, { replace: true }); // redirect!!!
};`

**Comment by sourabhrathour45** [comment]
Issue fixed.
